version: "3.5"
services:
  app:
    container_name: ${SERVICE_NAME}
    build:
      context: ../
      dockerfile: ./development/Dockerfile
    ports:
      - 80:80
    volumes:
      - ../:/home/app
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
